Tags has been changed following the specification
BioContainers/containers pull request #211
Opened 2018-03-26 20:08 UTC by ypriverol

@osallou Here I have changed all the recipes. Please review them and accept the PR.

2018-03-27 07:15 UTC, osallou requested changes
most makes use of about.license_file, but do not specify about.license even if using standard licenses (gpl3 , etc.).
using license_file is good, but license should also be directly specified

2018-03-27 07:15 UTC, osallou commented on comet/2016012/Dockerfile
>  LABEL BIOTOOLS="https://bio.tools/comet"
should be extra.identifiers.biotools

2018-03-27 07:15 UTC, osallou commented on test-ci/0.0.1/Dockerfile
> +LABEL about.license_file="gpl3+"
this is about.license, not about.license_file

2018-03-27 07:49 UTC, ypriverol commented
I will change them, the problem is that I have noticed that most of them have some kind of modification in the license, when you read the license file. I will try to do my best to annotate them.

2018-03-27 08:16 UTC, osallou commented
for custom ones, license should specify something like 'custom, see
license_file"

Le mar. 27 mars 2018 à 09:49, Yasset Perez-Riverol <notifications@github.com>
a écrit :

> I will change them, the problem is that I have noticed that most of them
> have some kind of modification in the license, when you read the license
> file. I will try to do my best to annotate them.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/BioContainers/containers/pull/211#issuecomment-376429858>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA-gYilh3j-0GgNQA_wzUteK82-CQNLAks5tie74gaJpZM4S70_e>
> .
>

2018-03-27 10:57 UTC, ypriverol commented
@osallou we are now ready to merge because I have updated all the license information. Please have a look and let me know.

2018-03-28 06:52 UTC, osallou commented on biocontainers/Dockerfile
>  LABEL about.summary="Base image for BioDocker"
as a base image, shouldn't it follow the same rules as other containers ie having:
biocontainers/x.y.z/Dockerfile

to keep track of older versions. Automatic builds won't be able to detect version from directory

2018-03-28 06:53 UTC, osallou commented on Rstudio-Proteomics/Dockerfile
>  LABEL about.summary="Rstudio-Proteomics is an adaptation from the original images provided by the Rocker-org. The container provided here contains a Rstudio server configurated with several packages
this one does not follow rule to get version directory (Rstudio-Proteomics/x.y.z/Dockerfile)

2018-03-28 06:54 UTC, osallou commented on pymol-jupiter/Dockerfile
>  LABEL about.summary="a portable way of interacting with PyMol via Jupyter notebook"
missing version directory too

2018-03-28 06:55 UTC, osallou commented on zorro/Dockerfile
>  LABEL about.summary="A probabilistic alignment masking program"
missing version directory too

2018-03-28 07:05 UTC, ypriverol commented
I will update them

2018-03-28 10:26 UTC, osallou approved these changes

2018-03-28 10:51 UTC, merged