Adding a working container for NanoSV
BioContainers/containers pull request #397
Opened 2021-02-19 22:47 UTC by oneillkza

# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [ ] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [ ] The image can be built  
 - [ x] The BioConda package is missing a dependency (sambamba), which this container provides.
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [X ] LABEL base_image  
 - [X ] LABEL version
 - [X ] LABEL software.version  
 - [X ] LABEL about.summary  
 - [X ] LABEL about.home  
 - [X ] LABEL about.license   
 - [X ] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata  

As noted above, while this is available as an autobuild from BioConda, the tool itself actually depends on sambamba, but that dependency is not listed in the BioConda package. The result is that the autobuilt container is not self-contained. This container adds sambamba, so that it is now self-contained. The python version had to be specified due to some dependency issues (see https://github.com/mroosmalen/nanosv/issues/65).

2021-02-19 22:47 UTC, osallou commented
can't modify multiple containers in a same pull request

2021-02-19 22:48 UTC, osallou commented
can't modify multiple containers in a same pull request

2021-02-19 22:48 UTC, osallou commented
can't modify multiple containers in a same pull request

2021-02-19 22:50 UTC, oneillkza commented
oops -- accidentally committed a vim swapfile. Should be good now.

2021-02-19 23:01 UTC, oneillkza commented
PS: this software is basically abandonware. I am not the software maintainer. I just want Biocontainers to contain a version of it that's actually, well, contained.

2021-02-20 05:48 UTC, osallou requested changes

2021-02-20 05:48 UTC, osallou commented on nanosv/1.2.4/Dockerfile
> +LABEL about.documentation="https://github.com/BioContainers/specs/wiki"
This biocontainers doc page ;-) should siftware doc page, if any, else put homepage

2021-02-20 05:48 UTC, osallou commented
Thanks for contrib. There is just a small update to be done before merge

2021-02-21 00:13 UTC, oneillkza commented
No worries! And I've fixed that. To be honest the sum-total of the documentation is the readme.md on the Github repo.

Hopefully it should be good to go!

2021-02-21 06:43 UTC, osallou approved these changes

2021-02-21 06:43 UTC, merged