Update conodictor to v2.3.1
BioContainers/containers pull request #411
Opened 2021-08-12 16:37 UTC by Ebedthan

Hello,
This PR upgrade the version of the conodictor. Thanks for your works!
Regards,

2021-08-12 17:14 UTC, osallou commented
Hi, thanks for contrib. As shown in comments build failed due to missing labels or invalid labels.

2021-08-12 20:54 UTC, Ebedthan commented
I think the build has now passed without an issue.

2021-08-13 02:41 UTC, osallou requested changes
Thanks, just a final update on version label and it will be good for merge, thanks for your efforts

2021-08-13 02:41 UTC, osallou commented on conodictor/2.3.1/Dockerfile
> +LABEL version="2"
Version is 1 here as it is first version of this dockerfile.

Version is a way to track changes on a specific dockerfile (upstream is the same but we patch build rule for example)

2021-08-13 11:13 UTC, merged

2021-08-13 11:14 UTC, osallou commented
Merged, thanks for your work, container should be built in a moment after ci on master branch