Add container for eido
BioContainers/containers pull request #457
Opened 2022-08-08 13:25 UTC by rafalstepien

# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [ ] LABEL base_image  
 - [ ] LABEL version
 - [ ] LABEL software.version  
 - [ ] LABEL about.summary  
 - [ ] LABEL about.home  
 - [ ] LABEL about.license   
 - [ ] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

2022-08-08 13:30 UTC, rafalstepien commented
Container request: https://github.com/BioContainers/containers/issues/458

2022-08-08 14:58 UTC, osallou requested changes
Should be in a subdir containing version ie eido/0.1.6/Dockerfile

2022-08-08 14:58 UTC, osallou commented on eido/Dockerfile
> +LABEL version="3"
Should be version 1

2022-08-08 17:40 UTC, osallou commented
Biotools id is eido-python-package according to biotools web site

2022-08-08 17:51 UTC, osallou commented
Did you test the container? I see you just unzip the release , but i see no python install nor requirements installation, wonder if it works....

Why not just installing the python package via pip (as root)?

Something like

USER root
RUN pip install eido==0.1.6 (pip or pip3 according to image ..)
USER biodocker

2022-08-09 17:37 UTC, rafalstepien commented
I updated and tested the container

2022-08-09 17:43 UTC, osallou requested changes

2022-08-09 17:43 UTC, osallou commented on eido/0.1.6/Dockerfile
> +LABEL extra.identifiers.biotools=eido
In biotools, id is eido-python-package

2022-08-09 17:55 UTC, merged

2022-08-09 17:55 UTC, osallou commented
@rafalstepien merged, thanks for contrib and patience