updated version to 15.3.0
BioContainers/containers pull request #519
Opened 2023-06-08 19:49 UTC by jennahamlin

# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

2023-06-09 07:09 UTC, osallou requested changes

2023-06-09 07:09 UTC, osallou commented on ncbi-datasets-cli/15.3.0/Dockerfile
> +LABEL software.version="14.2.2"
you forgot to updated related version metadata

2023-06-09 12:47 UTC, jennahamlin reviewed
MetaData changes: changed label version 2 -> 3, unsure if this is necessary. Changed label software.version 14.2.2 -> 15.3.0

2023-06-10 09:43 UTC, osallou commented
Buld failed on conda install, did you try locally the docker build?

2023-06-12 13:00 UTC, jennahamlin commented
Hmm, interesting that the build for 15.3.0 failed. I tried to locally build via docker build for both 15.3.0 and 14.2.2 and both failed at the same step (fetching package metadata) and with same exit code (137). This maybe a certificate issue or a me issue, as I am probably missing something.

2023-06-12 14:23 UTC, osallou commented
seems related to old conda version used in image, does not work anymore (at least not for all)

a conda update conda fix the issue

    RUN conda update -n base conda
    RUN conda install ...

2023-06-15 16:17 UTC, jennahamlin commented
Thank you for the comments but found the container: quay.io/staphb/ncbi-datasets:15.2.0
No need to duplicate

2023-06-15 16:17 UTC, closed without merging